language: python
sudo: false
dist: xenial

# enable c++11/14 builds
addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'libstdc++-4.9-dev' ]

before_install:
  - pip install --upgrade pip

install:
  - python -V
  - which python
  - pip install pytest
  - pip install --verbose .

script:
  - pytest

# the matrix allows you to specify different operating systems and environments to
# run your tests and build binaries
matrix:
  include:

    ## ** Builds that are published **

    # linux cfi build python 3.7
    - os: linux
      env: CXXFLAGS="-fsanitize=cfi -fvisibility=hidden" LDFLAGS="-fsanitize=cfi"
      python: 3.7
    # linux python 3.7
    - os: linux
      python: 3.7
    # linux python 3.6
    - os: linux
      python: 3.6
    # linux python 2.7
    - os: linux
      python: 2.7
    # g++ build (default builds all use clang++)
    - os: linux
      env: CXX="g++-6" CC="gcc-6" LINK="g++-6" AR="ar" NM="nm"
      python: 3.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++-6-dev
            - g++-6
